import Head from "next/head";
import Link from "next/link";
import React, { useState } from "react";
import { API_KEY } from "@/api/API";
import axios from "axios";

export const getStaticProps = async () => {
  const res = await fetch(` ${API_KEY}/products`);
  const data = await res.json();

  return {
    props: { api: data },
  };
};



const Amigo = ({api}) => {


  const [name, setName] = useState("");
  const [image, setImage] = useState("");
  const [price, setPrice] = useState("");
  const [desc, setDesc] = useState("");



  const CreateProduct = (e) => {
    e.preventDefault();
    axios
      .post(`${API_KEY}/products`, {
        name: name,
        image: image,
        price: price,
        desc: desc,
      })
      .then(() => {
        alert("sucesfully");
        window.location.reload();
      })
      .catch((err) => {
        alert("err");
      });
  };


  const dataDelete = async (_id) => {
    try{
        await axios
        .delete(`${API_KEY}/products/${_id}`)
        .then(() => window.location.reload())
        alert("delete??")
    } catch(err) {
        alert(err)
    }
  }

  const updateProduct = (_id) => {
    axios.patch(`${API_KEY}/products/${_id}`, {
      name: name,
      image: image,
      desc: desc,
      price: price
    }) .then(() => {
      alert("Updated")
      window.location.reload()
    }).catch((err) => {
      alert("err")
    })
  }






  return (
    <div>
      <Head>
        <title>Create Next App | CRUD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    

      <form onSubmit={CreateProduct}>
        <input required type="text" placeholder="name"  value={name} onChange={(e) => setName(e.target.value)}/>
        <input disabled={!name} required type="text" placeholder="image" value={image}onChange={(e) => setImage(e.target.value)}/>
        <input disabled={!image} required type="text" placeholder="desc"  value={desc} onChange={(e) => setDesc(e.target.value)}/>
        <input disabled={!desc} required type="number" placeholder="price" value={price} onChange={(e) => setPrice(e.target.value)}/>
        <button type="submit">Create</button>
      </form>

      <div className="cards">
        {api.map((el) => {
          return (
            <div key={el?._id} className="card">
              <img src={el?.image} alt="" />
              <h1>{el?.name}</h1>
              <p>{el?.desc}</p>
              <p>{el?.price}</p>
              <button onClick={() => dataDelete(el?._id)}>DELETE</button>
              <button disabled={!price} onClick={() => updateProduct(el?._id)}>UPDATE</button>
            </div>
          );
        })}
      </div>
    
    
    </div>
  );
};

export default Amigo;
